name: Test & Build Docker Image

on:
  schedule:
    - cron: '0 1 * * 6'
  push:
    branches: [ "php-7.1" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "php-7.1" ]

env:
  IMAGE_NAME: bantenitsolutions/nginx-php
  IMAGE_TAG: php-7.1
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Build Image
        run: |-
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Smoke Test Image
        run: |-
          docker-compose -f docker-compose.yml up -d app
          sleep 2
          docker-compose -f docker-compose.yml run sut
          
      - name: Login to Docker Hub
        if: (github.ref == 'refs/heads/php-7.1' && (github.event_name == 'push' || github.event_name == 'schedule' )) || contains(github.ref, 'refs/tags/')
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Multi-arch Image and Push
        if: github.ref == 'refs/heads/php-7.1' && (github.event_name == 'push' || github.event_name == 'schedule')
        run: |-
          docker buildx build \
            --cache-from=$IMAGE_NAME:$IMAGE_TAG \
            --push \
            -t $IMAGE_NAME:$IMAGE_TAG \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
            .